// ControllerToActorCritic.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "../RLSimion-Lib/parameters.h"
#include "../RLSimion-Lib/parameter.h"
#include "../RLSimion-Lib/world.h"
#include "../RLSimion-Lib/actor.h"
#include "../RLSimion-Lib/reward.h"
#include "../RLSimion-Lib/logger.h"
#include "../RLSimion-Lib/experiment.h"
#include "../RLSimion-Lib/states-and-actions.h"
#include "../RLSimion-Lib/vfa.h"
#include "../RLSimion-Lib/features.h"



class CStats
{
	double min,max,total, sqrtotal;
	int numValues;
public:
	CStats(){ reset(); }
	~CStats(){}
	void addValue(double value)
	{
		value= fabs(value);
		numValues++;
		if (value>max)
			max= value;
		if (value<min)
			min= value;
		total+= value;
		sqrtotal += value*value;
	}
	double getMax(){return max;}
	double getMin(){return min;}
	double getAvg(){return total/(double)numValues;}
	double getRMSE(){ return sqrt(sqrtotal / (double)numValues); }
	void reset(){ min = 99999999.9; max = 0.0; total = 0.0; numValues = 0; sqrtotal = 0.0; }
};


CWorld *g_pWorld;
CExperiment *g_pExperiment = 0;

int main(int argc, char* argv[])
{
	if (argc<2)
	{
		printf("ERROR: a configuration file should be provided as an argument.");
		exit(-1);
	}

	CParameters* pAppParameters= new CParameters(argv[1]);
	CParameters* pParameterNode = pAppParameters->getChild("COMPARE_AC_AND_ACTOR");
	
	//INITIALISE WORLD -> STATE PROPERTIES
	CParameters* pActorParameters = new CParameters(pParameterNode->getParameter("ACTOR_CONFIG_FILE")->getStringPtr());
	
	//set app parameters and additional parameters if any, generated by Badger
	pActorParameters->loadParameters(argv[1]);

	g_pExperiment = new CExperiment(pActorParameters->getChild("EXPERIMENT"));
	g_pWorld = new CWorld(pActorParameters->getChild("WORLD"));

	//INITIALISE ACTOR
	CActor *pActor = CActor::getActorInstance(pActorParameters->getChild("SIMGOD")->getChild("ACTOR"));

	//INTIALISE CONTROLLER: VIDAL, BOUKHEZZAR, ...
	CParameters* pControllerParameters = new CParameters(pParameterNode->getParameter("CONTROLLER_CONFIG_FILE")->getStringPtr());
	//it could also be "CONTROLLER"...not very neat
	CActor *pController = CActor::getControllerInstance(pControllerParameters->getChild("SIMGOD")->getChild("ACTOR")); 

	CState *s= g_pWorld->getStateInstance();
	CAction *a= g_pWorld->getActionInstance();
	CAction *a2= g_pWorld->getActionInstance();

	int numSamples = (int)pParameterNode->getParameter("NUM_SAMPLES")->getDouble();
	
//#define NUM_SAMPLES 100000
#define NUM_POINTS_PER_DIM 100000
	double value;
	CStats* pStats= new CStats[a->getNumVars()];

	srand(1);
	for (int i= 0; i<numSamples; i++)
	{
		printf("Sampling controller and actor: %d/%d samples\r",i,numSamples);
		for (int j= 0; j<s->getNumVars(); j++)
		{
			value= (double)(rand()%NUM_POINTS_PER_DIM)/ (double)NUM_POINTS_PER_DIM;
			value= s->getMin(j) + value*(s->getMax(j)-s->getMin(j));
			s->setValue(j,value);
		}

		pController->selectAction(s,a);
		pActor->selectAction(s, a2);

		for (int j= 0; j<a->getNumVars(); j++)
		{
			pStats[j].addValue(a->getValue(j) - a2->getValue(j));
		}
	}

	FILE *pFile;
	fopen_s(&pFile, pParameterNode->getParameter("OUTPUT_FILE")->getStringPtr(), "w");
	if (pFile)
	{
		for (int j = 0; j < a->getNumVars(); j++)
		{
			fprintf_s(pFile,"Comparison stats for dim %d: Max=%.5e Min=%.5e Avg=%.5e RMSE= %.5e\n"
				, j, pStats[j].getMax(), pStats[j].getMin()
				, pStats[j].getAvg(), pStats[j].getRMSE());
		}
		fclose(pFile);
	}

	delete [] pStats;


	//CLEAN-UP
	delete a;
	delete s;
	delete g_pWorld;

	delete pAppParameters;
	delete pActorParameters;
	delete pControllerParameters;

	delete pController;
	delete pActor;
}

