// ControllerToActorCritic.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "../RLSimion-Lib/parameters.h"
#include "../RLSimion-Lib/world.h"
#include "../RLSimion-Lib/actor.h"
#include "../RLSimion-Lib/reward.h"
#include "../RLSimion-Lib/logger.h"
#include "../RLSimion-Lib/experiment.h"
#include "../RLSimion-Lib/states-and-actions.h"
#include "../RLSimion-Lib/vfa.h"
#include "../RLSimion-Lib/features.h"



class CStats
{
	double min,max,total, sqrtotal;
	int numValues;
public:
	CStats(){ reset(); }
	~CStats(){}
	void addValue(double value)
	{
		value= fabs(value);
		numValues++;
		if (value>max)
			max= value;
		if (value<min)
			min= value;
		total+= value;
		sqrtotal += value*value;
	}
	double getMax(){return max;}
	double getMin(){return min;}
	double getAvg(){return total/(double)numValues;}
	double getRMSE(){ return sqrt(sqrtotal / (double)numValues); }
	void reset(){ min = 99999999.9; max = 0.0; total = 0.0; numValues = 0; sqrtotal = 0.0; }
};


CWorld *g_pWorld;
CExperiment *g_pExperiment = 0;

int main(int argc, char* argv[])
{
	if (argc<2)
	{
		printf("ERROR: a configuration file should be provided as an argument.");
		exit(-1);
	}

	CParameters* pAppParameters= new CParameters(argv[1]);
	
	//INITIALISE WORLD -> STATE PROPERTIES
	CParameters* pActorParameters = new CParameters(pAppParameters->getStringPtr("COMPARE_AC_AND_ACTOR/ACTOR_CONFIG_FILE"));
	
	//set app parameters and additional parameters if any, generated by Badger
	pActorParameters->setParameters(pAppParameters);

	g_pExperiment = new CExperiment(pActorParameters);
	g_pWorld = new CWorld(pActorParameters);

	//INITIALISE ACTOR's VFA
	int numOutputs = (int)pActorParameters->getDouble("SIMGOD/ACTOR/NUM_OUTPUTS");

	//INTIALISE VFA MANUALLY
	//because the Actor class is a singleton!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	char parameterName[MAX_PARAMETER_NAME_SIZE];
	CFeatureVFA **pVFA = new CFeatureVFA*[numOutputs];
	CFeatureList *pFeatures = new CFeatureList();

	FILE* pPolicyFile;
	if (pActorParameters->exists("SIMGOD/ACTOR/LOAD"))
	{
		printf("loading %s\n", pActorParameters->getStringPtr("SIMGOD/ACTOR/LOAD"));
		fopen_s(&pPolicyFile, pActorParameters->getStringPtr("SIMGOD/ACTOR/LOAD"), "rb");
	}
	for (int i = 0; i<numOutputs; i++)
	{
		sprintf_s(parameterName, MAX_PARAMETER_NAME_SIZE, "SIMGOD/ACTOR/POLICY_RBF_VARIABLES_%d", i);
		pVFA[i] = new CRBFFeatureGridVFA(pActorParameters->getStringPtr(parameterName));
		if (pPolicyFile)
			pVFA[i]->load(pPolicyFile);
	}
	if (pPolicyFile) fclose(pPolicyFile);

	//INTIALISE CONTROLLER: VIDAL, BOUKHEZZAR, ...
	CParameters* pControllerParameters = new CParameters(pAppParameters->getStringPtr("COMPARE_AC_AND_ACTOR/CONTROLLER_CONFIG_FILE"));
	CActor *pController = CActor::getActorInstance(pControllerParameters);

	CState *s= g_pWorld->getStateInstance();
	CAction *a= g_pWorld->getActionInstance();
	CAction *a2= g_pWorld->getActionInstance();

	int numSamples = (int) pAppParameters->getDouble("COMPARE_AC_AND_ACTOR/NUM_SAMPLES");
	
//#define NUM_SAMPLES 100000
#define NUM_POINTS_PER_DIM 100000
	double value;
	CStats* pStats= new CStats[a->getNumVars()];

	srand(1);
	for (int i= 0; i<numSamples; i++)
	{
		printf("Sampling controller and actor: %d/%d samples\r",i,numSamples);
		for (int j= 0; j<s->getNumVars(); j++)
		{
			value= (double)(rand()%NUM_POINTS_PER_DIM)/ (double)NUM_POINTS_PER_DIM;
			value= s->getMin(j) + value*(s->getMax(j)-s->getMin(j));
			s->setValue(j,value);
		}
		pController->selectAction(s,a);

		//for each action dimension
		//pActor->selectAction(s, a2);
		for (int j = 0; j < numOutputs; j++)
		{
			pVFA[j]->getFeatures(s, 0, pFeatures);
			a2->setValue(j, pVFA[j]->getValue(pFeatures));
		}
		

		for (int j= 0; j<a->getNumVars(); j++)
		{
			pStats[j].addValue(a->getValue(j) - a2->getValue(j));
		}
	}

	FILE *pFile;
	fopen_s(&pFile, pAppParameters->getStringPtr("COMPARE_AC_AND_ACTOR/OUTPUT_FILE"), "w");
	if (pFile)
	{
		for (int j = 0; j < a->getNumVars(); j++)
		{
			fprintf_s(pFile,"Comparison stats for dim %d: Max=%.5e Min=%.5e Avg=%.5e RMSE= %.5e\n"
				, j, pStats[j].getMax(), pStats[j].getMin()
				, pStats[j].getAvg(), pStats[j].getRMSE());
		}
		fclose(pFile);
	}

	delete [] pStats;


	//CLEAN-UP
	delete a;
	delete s;
	delete g_pWorld;

	delete pAppParameters;
	delete pActorParameters;
	delete pControllerParameters;

	delete pController;
	for (int i = 0; i < numOutputs; i++) delete pVFA[i];
	delete [] pVFA;
	delete pFeatures;
}

